### ISSUE TITLE
Compare CSV export does not show New entries

### ISSUE THREAD

**Issue by hendrik-smith** [canix1/ADACLScanner#20]
Running a Compare scan shows the correct results for new and removed ACLs in the HTML output.
When selecting the CSV output, all new entries are shown as "Matched" instead of "New".  Removed entries are correctly shown as "Missing".

Sample CSV entry:
"OU=Administration,OU=Groups,OU=XY1,DC=HSLAB2,DC=local","organizationalUnit","HSLAB2\TestUser2","HSLAB2\TestUser2","GenericAll","Descendents","00000000-0000-0000-0000-000000000000","bf967aba-0de6-11d0-a285-00aa003049e2","InheritedObjectAceTypePresent","Allow","False","ContainerInherit","InheritOnly","2019-03-08 12:06:35","7d1dbe1f-0ae1-4e28-9fe0-30409cdf0118","1117506","","Match"

HTML image attached...
![image](https://user-images.githubusercontent.com/48356997/54033031-ecdb5e00-41bb-11e9-8b97-f5378576a5a5.png)

**Comment by canix1** [comment]
This is now fixed!
