### ISSUE TITLE
CSV Templates 2000 to 2012 R2 - issue with Identity Reference

### ISSUE THREAD

**Issue by itpro-tips** [canix1/ADACLScanner#22]
Hello,

First of all thanks for your great work, I use it often to detect ACL issue!

The CSVs for Windows 2016 has _SID_ for _Identity Reference_, it is great because we can compare with non-english Active Directory.

But the olders CSVs (2000 to 2012 R2) used sometimes SID, sometimes english name like 'Everyone', etc. That's lead to bad comparison if the AD is not in english.

Is this possible to update the CSV templates ?

Last thing: in the CSV templates download window, there is a little typo problem : _Configration NC_ instead of _Configuration NC_.

**Comment by canix1** [comment]
Thanks mate!
In 5.7 the templates are updated and the spellings is corrected
