### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by macphail** [canix1/ADACLScanner#23]
Hello,

When I run .\adaclscan.ps1 I get the errors in the attached file.  I've tried running on a 2012 R2 and 2019 Domain Controllers as well as a Windows 10 system, all return the same error.

I'm logged into the computers as an administrator and am running PowerShell as an administrator as well.

Thanks!

Chris

[adaclscan-errors.txt](https://github.com/canix1/ADACLScanner/files/3477515/adaclscan-errors.txt)

**Comment by exchange12rocks** [comment]
Hi macphail! These errors mean that you downloaded not the script file, but a page where the code of the file is published. If you look inside the file you have, you should see that it's an HTML-document instead of a PowerShell script. Download the file correctly and everything should work

**Comment by macphail** [comment]
OMG, what an idiot.  Thanks for the tip.

Chris
