### ISSUE TITLE
Add parameters to match GUI

### ISSUE THREAD

**Issue by RamblingCookieMonster** [canix1/ADACLScanner#24]
Hi!

First off, thanks for the awesome tool!

I might be off on this, but it seems like the GUI provides a bit more flexibility in what you collect.  It would be helpful to have these available via parameters.

Cheers!

**Comment by canix1** [comment]
Thanks! 
Yes sure that would be great. I put it on the list.

I will close this since it's not an issue, it's more of a feature request.

Cheers

**Comment by PrzemyslawKlys** [comment]
@canix1 Feature requests are also issues on GitHub. Many repositories have lots of feature requests. That's what you use Labels for. That way you don't forget.. and others will know not to request it again.
