### ISSUE TITLE
Argument error - script will not execute

### ISSUE THREAD

**Issue by lukowiczm** [canix1/ADACLScanner#25]
PS C:\Users\******\Desktop> .\ADACLScan.ps1 -Base "DC=*,DC=*,DC=*" -Scope subtree -E
sPrincipal ****
Found security principal
Get-Perm : Cannot process argument transformation on parameter 'bolGetOwnerEna'. Cannot convert value "" to
"System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At C:\Users\***\Desktop\ADACLScan.ps1:14635 char:99
+ ... lSubOU $global:strDomainShortName $false $false $false $Owner $SDDate ...

**Comment by canix1** [comment]
The issue is fixed in 5.9
