### ISSUE TITLE
Error when run from clipboard

### ISSUE THREAD

**Issue by korvindeson** [canix1/ADACLScanner#26]
Hi,

I run a lot of the powershell scripts on remote machines, without copying script files. When I do lines:
-->  $CurrentFSPath = split-path -parent $MyInvocation.MyCommand.Path

throw an error. If you change it to
--> $CurrentFSPath = $(Get-Location).path

It will do the same thing, but will not throw errors when working from clipboard

**Comment by canix1** [comment]
Replaced "split-path -parent $MyInvocation.MyCommand.Path" with $PSScriptRoot. Feel free to test if it works.

**Comment by canix1** [comment]
Please test and share your results.

**Comment by canix1** [comment]
No response so closing
