### ISSUE TITLE
Legend does not match result - Access Right Criticality option

### ISSUE THREAD

**Issue by Beylie** [canix1/ADACLScanner#31]
Write properties should be tagged as "Warning" in yellow as per legend if access right criticality is enabled:

![image](https://user-images.githubusercontent.com/28935079/74730166-55491100-524e-11ea-8cf3-21d94399c182.png)

Report has it listed as gray though:

![image](https://user-images.githubusercontent.com/28935079/74730232-6bef6800-524e-11ea-8d57-af0026171ade.png)

Awesome script though. Love the GUI.

**Comment by canix1** [comment]
Hi Beylie!

Thanks for reporting it!
I will fix it asap.

Cheer
Robin

Sent from Mail for Windows 10

From: Beylie
Sent: Tuesday, February 18, 2020 12:00 PM
To: canix1/ADACLScanner
Cc: Subscribed
Subject: [canix1/ADACLScanner] Legend does not match result - Access Right Criticality option (#31)

Write properties should be tagged as "Warning" in yellow as per legend if access right criticality is enabled:

Report has it listed as gray though:

Awesome script though. Love the GUI.

**Comment by canix1** [comment]
Fixed in 6.1
