### ISSUE TITLE
View Inherited Permissions from Powershell command line

### ISSUE THREAD

**Issue by doyleND** [canix1/ADACLScanner#34]
Hi,
I cannot figure out a way to show the inherited permissions when using effective rights from Powershell.  I can see it when I run the GUI and select the user principle I want to view.

**Comment by canix1** [comment]
Hi doyleND,

This is now fixed in 6.3.

**Comment by canix1** [comment]
This is now fixed in 6.3.

**Comment by doyleND** [comment]
Thank you that's great 👍
