### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by itpro-tips** [canix1/ADACLScanner#41]
Hello,
From the 6.5 version, you remove _public class IconExtractor_.
I don't know if it's wanted or not but the icons don't show anymore (tested on WS 2016 WS 2019, 10 21H1).

**Comment by canix1** [comment]
Hi, 

It was a failed attempt to fix the incompability with PowerShell 7.
I'm working on a fix.

**Comment by canix1** [comment]
This should now be fixed in 6.8
