### ISSUE TITLE
-FilterTrustee does not work with -RecursiveFind

### ISSUE THREAD

**Issue by MichaelGrafnetter** [canix1/ADACLScanner#49]
Hello @canix1 , I have stumbled upon this behavior of ADACLScanner 7.3 and I am not sure if it is a bug or expected behavior. It seems that the `-FilterTrustee` parameter gets evaluated before the `-RecursiveFind` parameter.

For example, I am trying to look up the permissions to create computer objects. If I run this:

```powershell
 .\ADACLScan.ps1 -Base 'DC=contoso,DC=com' `
                 -Scope onelevel `
                 -Filter '(|(objectClass=domainDNS)(objectClass=organizationalUnit)(objectClass=container))' `
                 -AccessType Allow `
                 -ApplyTo computer `
                 -Permission create `
                 -RecursiveFind `
                 -Output HTML `
                 -Show
```
I get the following results, as john is a member of Account Operators:

![image](https://user-images.githubusercontent.com/8986376/193528710-1f4bf94b-a57f-4039-af55-563188c872f3.png)

But if I add the `-FilterTrustee` parameter:
```powershell
 .\ADACLScan.ps1 -Base 'DC=contoso,DC=com' `
                 -Scope onelevel `
                 -Filter '(|(objectClass=domainDNS)(objectClass=organizationalUnit)(objectClass=container))' `
                 -AccessType Allow `
                 -ApplyTo computer `
                 -Permission create `
                 -FilterTrustee 'CONTOSO\john' `
                 -RecursiveFind `
                 -Output HTML `
                 -Show
```

I just get `No Permissions found!`

**Comment by canix1** [comment]
God point! 
Thanks!
Rearranged the order for filtering the "Trustee".

Result:
![image](https://user-images.githubusercontent.com/16766188/193557325-cc754173-67a6-4f43-a392-147206fa31dc.png)
