### ISSUE TITLE
Does not work outside DC

### ISSUE THREAD

**Issue by CaledoniaProject** [canix1/ADACLScanner#5]
It looks like this script can only be run on the domain controller, is it possible to run it remotely?

**Comment by canix1** [comment]
Hi, Can you be a little more specific? Error messages etc?

**Comment by CaledoniaProject** [comment]
Does the script require domain admin privilege?

**Comment by CaledoniaProject** [comment]
Weird, it suddenly worked ..

**Comment by CaledoniaProject** [comment]
Oh it raises error as a normal user

```
ReverseDNList : Cannot bind argument to parameter 'stringlist' because it is nu
ll.
At xxxxx\ADACLScan.ps1:6122 char:30
+     $nodelist = ReverseDNList <<<<  $nodelist
    + CategoryInfo          : InvalidData: (:) [ReverseDNList], ParameterBindi
   ngValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,R
   everseDNList
```

**Comment by exchange12rocks** [comment]
@CaledoniaProject Hi Aaron. The script does not require Domain Admin privileges. That error, which you have shown, might be related to the PowerShell version. Please check which version you are using now by executing the following PS code on the machine where you experience the problem: `($PSVersionTable).PSVersion.Major`

Should it return anything lower than 3, it means you need to download and install [WMF3](https://www.microsoft.com/en-us/download/details.aspx?id=34595) on that machine.
