### ISSUE TITLE
Add -HideProgressBar

### ISSUE THREAD

**Issue by bastienperez** [canix1/ADACLScanner#51]
Hello Robin,

Any chance to add a switch `-HideProgressBar` to speed up the searches via command line?

Thanks

**Comment by canix1** [comment]
Hi Bastien,

I made the progress bar disabled by default with the option to show it with -ShowProgressbar

**Comment by canix1** [comment]
Fixed i 7.7

**Comment by bastienperez** [comment]
Awesome! Thanks.
