### ISSUE TITLE
Pop-up windows disappear during window switching

### ISSUE THREAD

**Issue by exchange12rocks** [canix1/ADACLScanner#9]
When a pop-up window, like the object scanner, or the domain picker, is opened and user switches to another application, that window disappears and the main script window continues to be locked. The pop-up window can be found if the user minimizes all opened windows, but it would be much easier if we could just to Alt-Tab to it.

**Comment by canix1** [comment]
Yes, really annoying..  I will look at it

**Comment by exchange12rocks** [comment]
Fixed by #15
